---
  - name: Install PostgreSQL
    become: true
    apt:
      name: "{{item}}"
      update_cache: yes
      cache_valid_time: 3600
      state: present
    with_items:
      - "postgresql"
      - "postgresql-client"
      - "postgresql-contrib"
      - "python-psycopg2"
  - name: Change postgres user password
    become: true
    become_user: "postgres"
    postgresql_user:
      db: postgres
      user: postgres
      password: postgres
